version: "3.8"

services:
  elasticsearch:
    image: elastic/elasticsearch:8.17.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.authc.anonymous.username=anonymous_user
      - xpack.security.authc.anonymous.roles=superuser
      - xpack.security.authc.anonymous.authz_exception=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elasticnet

  kibana:
    image: kibana:8.17.4
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elasticnet

volumes:
  esdata:
    driver: local

networks:
  elasticnet:
    driver: bridge
