// <auto-generated />
using System;
using Ecommerce.Infrastructure.Persistence.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerce.Infrastructure.Migrations
{
    [DbContext(typeof(EfCoreContext))]
    [Migration("20250318031907_1")]
    partial class _1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.Domain.Common.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("True");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Ecommerce.Domain.NotificationAggregate.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("NotificationId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Description");

                    b.Property<string>("NotificationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NotificationStatus");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NotificationType");

                    b.Property<DateTime>("ReadAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ReadAt");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.OrderAggregate.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("OrderId");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("OrderDate");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.PaymentAggregate.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FailureReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.ProductAggregate.Entities.ProductCategory", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategories", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.ProductAggregate.Entities.ProductTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ProductTags");
                });

            modelBuilder.Entity("Ecommerce.Domain.ProductAggregate.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SellerId");

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AccountVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ProductTagLink", b =>
                {
                    b.Property<Guid>("ProductsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("ProductTagLink");
                });

            modelBuilder.Entity("Ecommerce.Domain.Common.Entities.Category", b =>
                {
                    b.HasOne("Ecommerce.Domain.Common.Entities.Category", "Parent")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Ecommerce.Domain.NotificationAggregate.Notification", b =>
                {
                    b.HasOne("Ecommerce.Domain.UserAggregate.User", null)
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ecommerce.Domain.OrderAggregate.Order", b =>
                {
                    b.HasOne("Ecommerce.Domain.UserAggregate.User", null)
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Ecommerce.Domain.OrderAggregate.Entities.OrderItem", "OrderItems", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("OrderItemId");

                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("ProductId");

                            b1.Property<int>("Quantity")
                                .HasColumnType("int")
                                .HasColumnName("Quantity");

                            b1.HasKey("Id", "OrderId");

                            b1.HasIndex("OrderId");

                            b1.HasIndex("ProductId");

                            b1.ToTable("OrderItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.HasOne("Ecommerce.Domain.ProductAggregate.Product", null)
                                .WithMany()
                                .HasForeignKey("ProductId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.OwnsOne("Ecommerce.Domain.Common.ValueObjects.Price", "Price", b2 =>
                                {
                                    b2.Property<Guid>("OrderItemId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("OrderItemOrderId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<long>("ValueInCents")
                                        .HasColumnType("bigint")
                                        .HasColumnName("PriceValue");

                                    b2.HasKey("OrderItemId", "OrderItemOrderId");

                                    b2.ToTable("OrderItems");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderItemId", "OrderItemOrderId");
                                });

                            b1.Navigation("Price")
                                .IsRequired();
                        });

                    b.OwnsOne("Ecommerce.Domain.OrderAggregate.ValueObjects.BillingAddress", "BillingAddress", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("BillingCity");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("BillingCountry");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("BillingState");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("BillingStreet");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("BillingZipCode");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsOne("Ecommerce.Domain.OrderAggregate.ValueObjects.OrderTotal", "Total", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Currency");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("TotalPrice");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsOne("Ecommerce.Domain.OrderAggregate.ValueObjects.ShippingAddress", "ShippingAddress", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("ShippingCity");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("ShippingCountry");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("ShippingState");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("ShippingStreet");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("ShippingZipCode");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("BillingAddress")
                        .IsRequired();

                    b.Navigation("OrderItems");

                    b.Navigation("ShippingAddress")
                        .IsRequired();

                    b.Navigation("Total")
                        .IsRequired();
                });

            modelBuilder.Entity("Ecommerce.Domain.PaymentAggregate.Payment", b =>
                {
                    b.OwnsOne("Ecommerce.Domain.Common.ValueObjects.Price", "Price", b1 =>
                        {
                            b1.Property<Guid>("PaymentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<long>("ValueInCents")
                                .HasColumnType("bigint");

                            b1.HasKey("PaymentId");

                            b1.ToTable("Payments");

                            b1.WithOwner()
                                .HasForeignKey("PaymentId");
                        });

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("Ecommerce.Domain.ProductAggregate.Entities.ProductCategory", b =>
                {
                    b.HasOne("Ecommerce.Domain.Common.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce.Domain.ProductAggregate.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Ecommerce.Domain.ProductAggregate.Product", b =>
                {
                    b.HasOne("Ecommerce.Domain.UserAggregate.User", null)
                        .WithMany("Products")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Ecommerce.Domain.ProductAggregate.Entities.ProductImages", "Images", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("ProductImageId");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id", "ProductId");

                            b1.HasIndex("ProductId")
                                .IsUnique();

                            b1.ToTable("ProductImages", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProductId");

                            b1.OwnsOne("Ecommerce.Domain.ProductAggregate.Entities.ProductImage", "BackImage", b2 =>
                                {
                                    b2.Property<Guid>("ProductImagesId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("ProductImagesProductId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("ObjectIdentifier")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(450)");

                                    b2.Property<string>("Url")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("ProductImagesId", "ProductImagesProductId");

                                    b2.HasIndex("ObjectIdentifier")
                                        .IsUnique()
                                        .HasFilter("[BackImage_ObjectIdentifier] IS NOT NULL");

                                    b2.ToTable("ProductImages");

                                    b2.WithOwner()
                                        .HasForeignKey("ProductImagesId", "ProductImagesProductId");
                                });

                            b1.OwnsOne("Ecommerce.Domain.ProductAggregate.Entities.ProductImage", "BottomImage", b2 =>
                                {
                                    b2.Property<Guid>("ProductImagesId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("ProductImagesProductId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("ObjectIdentifier")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(450)");

                                    b2.Property<string>("Url")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("ProductImagesId", "ProductImagesProductId");

                                    b2.HasIndex("ObjectIdentifier")
                                        .IsUnique()
                                        .HasFilter("[BottomImage_ObjectIdentifier] IS NOT NULL");

                                    b2.ToTable("ProductImages");

                                    b2.WithOwner()
                                        .HasForeignKey("ProductImagesId", "ProductImagesProductId");
                                });

                            b1.OwnsOne("Ecommerce.Domain.ProductAggregate.Entities.ProductImage", "FrontImage", b2 =>
                                {
                                    b2.Property<Guid>("ProductImagesId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("ProductImagesProductId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("ObjectIdentifier")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(450)");

                                    b2.Property<string>("Url")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("ProductImagesId", "ProductImagesProductId");

                                    b2.HasIndex("ObjectIdentifier")
                                        .IsUnique()
                                        .HasFilter("[FrontImage_ObjectIdentifier] IS NOT NULL");

                                    b2.ToTable("ProductImages");

                                    b2.WithOwner()
                                        .HasForeignKey("ProductImagesId", "ProductImagesProductId");
                                });

                            b1.OwnsOne("Ecommerce.Domain.ProductAggregate.Entities.ProductImage", "LeftImage", b2 =>
                                {
                                    b2.Property<Guid>("ProductImagesId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("ProductImagesProductId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("ObjectIdentifier")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(450)");

                                    b2.Property<string>("Url")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("ProductImagesId", "ProductImagesProductId");

                                    b2.HasIndex("ObjectIdentifier")
                                        .IsUnique()
                                        .HasFilter("[LeftImage_ObjectIdentifier] IS NOT NULL");

                                    b2.ToTable("ProductImages");

                                    b2.WithOwner()
                                        .HasForeignKey("ProductImagesId", "ProductImagesProductId");
                                });

                            b1.OwnsOne("Ecommerce.Domain.ProductAggregate.Entities.ProductImage", "RightImage", b2 =>
                                {
                                    b2.Property<Guid>("ProductImagesId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("ProductImagesProductId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("ObjectIdentifier")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(450)");

                                    b2.Property<string>("Url")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("ProductImagesId", "ProductImagesProductId");

                                    b2.HasIndex("ObjectIdentifier")
                                        .IsUnique()
                                        .HasFilter("[RightImage_ObjectIdentifier] IS NOT NULL");

                                    b2.ToTable("ProductImages");

                                    b2.WithOwner()
                                        .HasForeignKey("ProductImagesId", "ProductImagesProductId");
                                });

                            b1.OwnsOne("Ecommerce.Domain.ProductAggregate.Entities.ProductImage", "Thumbnail", b2 =>
                                {
                                    b2.Property<Guid>("ProductImagesId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("ProductImagesProductId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("ObjectIdentifier")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(450)");

                                    b2.Property<string>("Url")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("ProductImagesId", "ProductImagesProductId");

                                    b2.HasIndex("ObjectIdentifier")
                                        .IsUnique();

                                    b2.ToTable("ProductImages");

                                    b2.WithOwner()
                                        .HasForeignKey("ProductImagesId", "ProductImagesProductId");
                                });

                            b1.OwnsOne("Ecommerce.Domain.ProductAggregate.Entities.ProductImage", "TopImage", b2 =>
                                {
                                    b2.Property<Guid>("ProductImagesId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("ProductImagesProductId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("ObjectIdentifier")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(450)");

                                    b2.Property<string>("Url")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("ProductImagesId", "ProductImagesProductId");

                                    b2.HasIndex("ObjectIdentifier")
                                        .IsUnique()
                                        .HasFilter("[TopImage_ObjectIdentifier] IS NOT NULL");

                                    b2.ToTable("ProductImages");

                                    b2.WithOwner()
                                        .HasForeignKey("ProductImagesId", "ProductImagesProductId");
                                });

                            b1.Navigation("BackImage");

                            b1.Navigation("BottomImage");

                            b1.Navigation("FrontImage");

                            b1.Navigation("LeftImage");

                            b1.Navigation("RightImage");

                            b1.Navigation("Thumbnail")
                                .IsRequired();

                            b1.Navigation("TopImage");
                        });

                    b.OwnsMany("Ecommerce.Domain.ProductAggregate.Entities.ProductReview", "Reviews", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("ReviewId");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)");

                            b1.HasKey("Id", "ProductId");

                            b1.HasIndex("ProductId");

                            b1.ToTable("ProductReviews", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProductId");

                            b1.OwnsOne("Ecommerce.Domain.ProductAggregate.ValueObjects.Rating", "Rating", b2 =>
                                {
                                    b2.Property<Guid>("ProductReviewId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("ProductReviewProductId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Value")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("Rating");

                                    b2.HasKey("ProductReviewId", "ProductReviewProductId");

                                    b2.ToTable("ProductReviews");

                                    b2.WithOwner()
                                        .HasForeignKey("ProductReviewId", "ProductReviewProductId");
                                });

                            b1.OwnsOne("Ecommerce.Domain.UserAggregate.ValueObjects.UserId", "AuthorId", b2 =>
                                {
                                    b2.Property<Guid>("ProductReviewId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("ProductReviewProductId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("Value")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("AuthorId");

                                    b2.HasKey("ProductReviewId", "ProductReviewProductId");

                                    b2.ToTable("ProductReviews");

                                    b2.WithOwner()
                                        .HasForeignKey("ProductReviewId", "ProductReviewProductId");
                                });

                            b1.Navigation("AuthorId")
                                .IsRequired();

                            b1.Navigation("Rating")
                                .IsRequired();
                        });

                    b.OwnsOne("Ecommerce.Domain.ProductAggregate.Entities.Promotion", "Promotion", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("ProductPromotionId");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("DiscountPercentage")
                                .HasColumnType("int");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("datetime2");

                            b1.HasKey("Id", "ProductId");

                            b1.HasIndex("ProductId")
                                .IsUnique();

                            b1.ToTable("ProductPromotions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("Ecommerce.Domain.ProductAggregate.ValueObjects.Rating", "AverageRating", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("decimal(18,2)")
                                .HasDefaultValue(0m)
                                .HasColumnName("AverageRating");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("Ecommerce.Domain.Common.ValueObjects.Price", "Price", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<long>("ValueInCents")
                                .HasColumnType("bigint");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("Ecommerce.Domain.ProductAggregate.ValueObjects.ProductDescription", "Description", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasColumnName("Description");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("Ecommerce.Domain.ProductAggregate.ValueObjects.ProductName", "Name", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("Name");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("Ecommerce.Domain.ProductAggregate.ValueObjects.Stock", "Stock", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");

                            b1.OwnsOne("Ecommerce.Domain.ProductAggregate.ValueObjects.Quantity", "Quantity", b2 =>
                                {
                                    b2.Property<Guid>("StockProductId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Value")
                                        .HasColumnType("int")
                                        .HasColumnName("StockQuantity");

                                    b2.HasKey("StockProductId");

                                    b2.ToTable("Products");

                                    b2.WithOwner()
                                        .HasForeignKey("StockProductId");
                                });

                            b1.Navigation("Quantity")
                                .IsRequired();
                        });

                    b.Navigation("AverageRating")
                        .IsRequired();

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Images")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("Promotion")
                        .IsRequired();

                    b.Navigation("Reviews");

                    b.Navigation("Stock")
                        .IsRequired();
                });

            modelBuilder.Entity("Ecommerce.Domain.UserAggregate.User", b =>
                {
                    b.OwnsOne("Ecommerce.Domain.UserAggregate.Entities.Cart", "Cart", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("CartId");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("UserId")
                                .IsUnique();

                            b1.ToTable("UserCarts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.OwnsMany("Ecommerce.Domain.UserAggregate.Entities.CartItem", "Items", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("CartItemId");

                                    b2.Property<Guid>("CartId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("ProductId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("ProductId");

                                    b2.Property<int>("Quantity")
                                        .HasColumnType("int")
                                        .HasColumnName("Quantity");

                                    b2.HasKey("Id", "CartId");

                                    b2.HasIndex("CartId");

                                    b2.HasIndex("ProductId");

                                    b2.ToTable("UserCartItems", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("CartId");

                                    b2.HasOne("Ecommerce.Domain.ProductAggregate.Product", null)
                                        .WithMany()
                                        .HasForeignKey("ProductId")
                                        .OnDelete(DeleteBehavior.Restrict)
                                        .IsRequired();
                                });

                            b1.Navigation("Items");
                        });

                    b.OwnsOne("Ecommerce.Domain.UserAggregate.Entities.Wishlist", "Wishlist", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("WishlistId");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("UserId")
                                .IsUnique();

                            b1.ToTable("Wishlists", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.OwnsMany("Ecommerce.Domain.ProductAggregate.ValueObjects.ProductId", "ProductIds", b2 =>
                                {
                                    b2.Property<Guid>("Value")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("ProductId");

                                    b2.Property<Guid>("WishlistId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid?>("ProductId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.HasKey("Value", "WishlistId");

                                    b2.HasIndex("ProductId");

                                    b2.HasIndex("WishlistId");

                                    b2.ToTable("WishlistProducts", null, t =>
                                        {
                                            t.Property("ProductId")
                                                .HasColumnName("ProductId1");
                                        });

                                    b2.HasOne("Ecommerce.Domain.ProductAggregate.Product", null)
                                        .WithMany()
                                        .HasForeignKey("ProductId")
                                        .OnDelete(DeleteBehavior.Restrict);

                                    b2.WithOwner()
                                        .HasForeignKey("WishlistId");
                                });

                            b1.Navigation("ProductIds");
                        });

                    b.OwnsOne("Ecommerce.Domain.OrderAggregate.ValueObjects.BillingAddress", "BillingAddress", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("BillingAddress_City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("BillingAddress_Country");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("BillingAddress_State");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("BillingAddress_Street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("BillingAddress_ZipCode");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Ecommerce.Domain.Common.ValueObjects.OneTimePassword", "EmailVerificationOtp", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("Expiry")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("NextResendValidAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("EmailVerificationOtpNextResendValidAt");

                            b1.Property<int>("ResendFailStreak")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Ecommerce.Domain.Common.ValueObjects.OneTimePassword", "PasswordResetOtp", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("Expiry")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("NextResendValidAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("PasswordResetOtpNextResendValidAt");

                            b1.Property<int>("ResendFailStreak")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Ecommerce.Domain.UserAggregate.ValueObjects.UserAddress", "Address", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Address");

                    b.Navigation("BillingAddress");

                    b.Navigation("Cart")
                        .IsRequired();

                    b.Navigation("EmailVerificationOtp");

                    b.Navigation("PasswordResetOtp");

                    b.Navigation("Wishlist")
                        .IsRequired();
                });

            modelBuilder.Entity("ProductTagLink", b =>
                {
                    b.HasOne("Ecommerce.Domain.ProductAggregate.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce.Domain.ProductAggregate.Entities.ProductTag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ecommerce.Domain.Common.Entities.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Ecommerce.Domain.UserAggregate.User", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Orders");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
