POST {{baseUrl}}/products
Content-Type: application/json
Cookie: {{accessToken}}

{
  "productName": "Acer Predator Helios 300",
  "productDescription": "Acer Predator Helios 300 Gaming Laptop, Intel i7-10750H, NVIDIA GeForce RTX 2060 6GB, 15.6 Full HD 144Hz 3ms IPS Display, 16GB Dual-Channel DDR4, 512GB NVMe SSD, Wi-Fi 6, RGB Keyboard, PH315-53-72XD",
  "priceValue": 10,
  "stockQuantity": 1, 
  "priceCurrency": "USD",
  "thumbnail": {
    "base64":"iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAA7EAAAOxAGVKw4bAAABaElEQVQ4jZ2TTUvDQBDGn3F3",
    "fileType":"image/png"
  },
  "leftImage": {
    "base64":"sample",
    "fileType":"sample"
  },
  "rightImage": {
    "base64":"sample",
    "fileType":"sample"
  },
  "frontImage": {
    "base64":"sample",
    "fileType":"sample"
  },
  "backImage": {
    "base64":"sample",
    "fileType":"sample"
  }
}


            