#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


echo "Husky.NET Started"
echo "Running Pre-Commit Hook"

dotnet tool run dotnet-csharpier ./Ecommerce.Application/ ./Ecommerce.Domain/ ./Ecommerce.Infrastructure/ ./Ecommerce.Api/ ./Ecommerce.Contracts/ ./Ecommerce.Tests/

echo "Husky.NET Finished"



